//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM 关系源元数据

[assembly: EdmRelationshipAttribute("WinesModel", "WineYear", "Wine", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WineMVVM.Database.Wine), "Year", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(WineMVVM.Database.Year), true)]
[assembly: EdmRelationshipAttribute("WinesModel", "WineTaste", "Wine", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WineMVVM.Database.Wine), "Taste", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(WineMVVM.Database.Taste), true)]
[assembly: EdmRelationshipAttribute("WinesModel", "WineColor", "Wine", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WineMVVM.Database.Wine), "Color", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(WineMVVM.Database.Color), true)]
[assembly: EdmRelationshipAttribute("WinesModel", "WineCountry", "Wine", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WineMVVM.Database.Wine), "Country", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(WineMVVM.Database.Country), true)]
[assembly: EdmRelationshipAttribute("WinesModel", "WineRegion", "Wine", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WineMVVM.Database.Wine), "Region", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(WineMVVM.Database.Region), true)]
[assembly: EdmRelationshipAttribute("WinesModel", "CountryRegion", "Country", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(WineMVVM.Database.Country), "Region", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WineMVVM.Database.Region), true)]
[assembly: EdmRelationshipAttribute("WinesModel", "MoodWMMW", "Mood", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(WineMVVM.Database.Mood), "WMMW", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WineMVVM.Database.WMMW), true)]
[assembly: EdmRelationshipAttribute("WinesModel", "WineWMMW", "Wine", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(WineMVVM.Database.Wine), "WMMW", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WineMVVM.Database.WMMW), true)]

#endregion

namespace WineMVVM.Database
{
    #region 上下文
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    public partial class WinesEntities : ObjectContext
    {
        #region 构造函数
    
        /// <summary>
        /// 请使用应用程序配置文件的“WinesEntities”部分中的连接字符串初始化新 WinesEntities 对象。
        /// </summary>
        public WinesEntities() : base("name=WinesEntities", "WinesEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 WinesEntities 对象。
        /// </summary>
        public WinesEntities(string connectionString) : base(connectionString, "WinesEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 WinesEntities 对象。
        /// </summary>
        public WinesEntities(EntityConnection connection) : base(connection, "WinesEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 分部方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<Color> Colors
        {
            get
            {
                if ((_Colors == null))
                {
                    _Colors = base.CreateObjectSet<Color>("Colors");
                }
                return _Colors;
            }
        }
        private ObjectSet<Color> _Colors;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<Country> Countries
        {
            get
            {
                if ((_Countries == null))
                {
                    _Countries = base.CreateObjectSet<Country>("Countries");
                }
                return _Countries;
            }
        }
        private ObjectSet<Country> _Countries;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<Mood> Moods
        {
            get
            {
                if ((_Moods == null))
                {
                    _Moods = base.CreateObjectSet<Mood>("Moods");
                }
                return _Moods;
            }
        }
        private ObjectSet<Mood> _Moods;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<Region> Regions
        {
            get
            {
                if ((_Regions == null))
                {
                    _Regions = base.CreateObjectSet<Region>("Regions");
                }
                return _Regions;
            }
        }
        private ObjectSet<Region> _Regions;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<Taste> Tastes
        {
            get
            {
                if ((_Tastes == null))
                {
                    _Tastes = base.CreateObjectSet<Taste>("Tastes");
                }
                return _Tastes;
            }
        }
        private ObjectSet<Taste> _Tastes;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<Wine> Wines
        {
            get
            {
                if ((_Wines == null))
                {
                    _Wines = base.CreateObjectSet<Wine>("Wines");
                }
                return _Wines;
            }
        }
        private ObjectSet<Wine> _Wines;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<Year> Years
        {
            get
            {
                if ((_Years == null))
                {
                    _Years = base.CreateObjectSet<Year>("Years");
                }
                return _Years;
            }
        }
        private ObjectSet<Year> _Years;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<WMMW> WMMWs
        {
            get
            {
                if ((_WMMWs == null))
                {
                    _WMMWs = base.CreateObjectSet<WMMW>("WMMWs");
                }
                return _WMMWs;
            }
        }
        private ObjectSet<WMMW> _WMMWs;

        #endregion
        #region AddTo 方法
    
        /// <summary>
        /// 用于向 Colors EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToColors(Color color)
        {
            base.AddObject("Colors", color);
        }
    
        /// <summary>
        /// 用于向 Countries EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToCountries(Country country)
        {
            base.AddObject("Countries", country);
        }
    
        /// <summary>
        /// 用于向 Moods EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToMoods(Mood mood)
        {
            base.AddObject("Moods", mood);
        }
    
        /// <summary>
        /// 用于向 Regions EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToRegions(Region region)
        {
            base.AddObject("Regions", region);
        }
    
        /// <summary>
        /// 用于向 Tastes EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToTastes(Taste taste)
        {
            base.AddObject("Tastes", taste);
        }
    
        /// <summary>
        /// 用于向 Wines EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToWines(Wine wine)
        {
            base.AddObject("Wines", wine);
        }
    
        /// <summary>
        /// 用于向 Years EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToYears(Year year)
        {
            base.AddObject("Years", year);
        }
    
        /// <summary>
        /// 用于向 WMMWs EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToWMMWs(WMMW wMMW)
        {
            base.AddObject("WMMWs", wMMW);
        }

        #endregion
    }
    

    #endregion
    
    #region 实体
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="WinesModel", Name="Color")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Color : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 Color 对象。
        /// </summary>
        /// <param name="color_id">color_id 属性的初始值。</param>
        /// <param name="color_description">color_description 属性的初始值。</param>
        public static Color CreateColor(global::System.Int32 color_id, global::System.String color_description)
        {
            Color color = new Color();
            color.color_id = color_id;
            color.color_description = color_description;
            return color;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 color_id
        {
            get
            {
                return _color_id;
            }
            set
            {
                if (_color_id != value)
                {
                    Oncolor_idChanging(value);
                    ReportPropertyChanging("color_id");
                    _color_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("color_id");
                    Oncolor_idChanged();
                }
            }
        }
        private global::System.Int32 _color_id;
        partial void Oncolor_idChanging(global::System.Int32 value);
        partial void Oncolor_idChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String color_description
        {
            get
            {
                return _color_description;
            }
            set
            {
                Oncolor_descriptionChanging(value);
                ReportPropertyChanging("color_description");
                _color_description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("color_description");
                Oncolor_descriptionChanged();
            }
        }
        private global::System.String _color_description;
        partial void Oncolor_descriptionChanging(global::System.String value);
        partial void Oncolor_descriptionChanged();

        #endregion
    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("WinesModel", "WineColor", "Wine")]
        public EntityCollection<Wine> Wine
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Wine>("WinesModel.WineColor", "Wine");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Wine>("WinesModel.WineColor", "Wine", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="WinesModel", Name="Country")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Country : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 Country 对象。
        /// </summary>
        /// <param name="country_id">country_id 属性的初始值。</param>
        /// <param name="country_name">country_name 属性的初始值。</param>
        public static Country CreateCountry(global::System.Int32 country_id, global::System.String country_name)
        {
            Country country = new Country();
            country.country_id = country_id;
            country.country_name = country_name;
            return country;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 country_id
        {
            get
            {
                return _country_id;
            }
            set
            {
                if (_country_id != value)
                {
                    Oncountry_idChanging(value);
                    ReportPropertyChanging("country_id");
                    _country_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("country_id");
                    Oncountry_idChanged();
                }
            }
        }
        private global::System.Int32 _country_id;
        partial void Oncountry_idChanging(global::System.Int32 value);
        partial void Oncountry_idChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String country_name
        {
            get
            {
                return _country_name;
            }
            set
            {
                Oncountry_nameChanging(value);
                ReportPropertyChanging("country_name");
                _country_name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("country_name");
                Oncountry_nameChanged();
            }
        }
        private global::System.String _country_name;
        partial void Oncountry_nameChanging(global::System.String value);
        partial void Oncountry_nameChanged();

        #endregion
    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("WinesModel", "WineCountry", "Wine")]
        public EntityCollection<Wine> Wine
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Wine>("WinesModel.WineCountry", "Wine");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Wine>("WinesModel.WineCountry", "Wine", value);
                }
            }
        }
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("WinesModel", "CountryRegion", "Region")]
        public EntityCollection<Region> Region
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Region>("WinesModel.CountryRegion", "Region");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Region>("WinesModel.CountryRegion", "Region", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="WinesModel", Name="Mood")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Mood : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 Mood 对象。
        /// </summary>
        /// <param name="mood_id">mood_id 属性的初始值。</param>
        /// <param name="mood_description">mood_description 属性的初始值。</param>
        /// <param name="wine_code">wine_code 属性的初始值。</param>
        public static Mood CreateMood(global::System.Int32 mood_id, global::System.String mood_description, global::System.String wine_code)
        {
            Mood mood = new Mood();
            mood.mood_id = mood_id;
            mood.mood_description = mood_description;
            mood.wine_code = wine_code;
            return mood;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 mood_id
        {
            get
            {
                return _mood_id;
            }
            set
            {
                if (_mood_id != value)
                {
                    Onmood_idChanging(value);
                    ReportPropertyChanging("mood_id");
                    _mood_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("mood_id");
                    Onmood_idChanged();
                }
            }
        }
        private global::System.Int32 _mood_id;
        partial void Onmood_idChanging(global::System.Int32 value);
        partial void Onmood_idChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String mood_description
        {
            get
            {
                return _mood_description;
            }
            set
            {
                Onmood_descriptionChanging(value);
                ReportPropertyChanging("mood_description");
                _mood_description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("mood_description");
                Onmood_descriptionChanged();
            }
        }
        private global::System.String _mood_description;
        partial void Onmood_descriptionChanging(global::System.String value);
        partial void Onmood_descriptionChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String wine_code
        {
            get
            {
                return _wine_code;
            }
            set
            {
                Onwine_codeChanging(value);
                ReportPropertyChanging("wine_code");
                _wine_code = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("wine_code");
                Onwine_codeChanged();
            }
        }
        private global::System.String _wine_code;
        partial void Onwine_codeChanging(global::System.String value);
        partial void Onwine_codeChanged();

        #endregion
    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("WinesModel", "MoodWMMW", "WMMW")]
        public EntityCollection<WMMW> WMMWs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<WMMW>("WinesModel.MoodWMMW", "WMMW");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<WMMW>("WinesModel.MoodWMMW", "WMMW", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="WinesModel", Name="Region")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Region : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 Region 对象。
        /// </summary>
        /// <param name="region_id">region_id 属性的初始值。</param>
        /// <param name="country_code">country_code 属性的初始值。</param>
        /// <param name="name">name 属性的初始值。</param>
        public static Region CreateRegion(global::System.Int32 region_id, global::System.Int32 country_code, global::System.String name)
        {
            Region region = new Region();
            region.region_id = region_id;
            region.country_code = country_code;
            region.name = name;
            return region;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 region_id
        {
            get
            {
                return _region_id;
            }
            set
            {
                if (_region_id != value)
                {
                    Onregion_idChanging(value);
                    ReportPropertyChanging("region_id");
                    _region_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("region_id");
                    Onregion_idChanged();
                }
            }
        }
        private global::System.Int32 _region_id;
        partial void Onregion_idChanging(global::System.Int32 value);
        partial void Onregion_idChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 country_code
        {
            get
            {
                return _country_code;
            }
            set
            {
                Oncountry_codeChanging(value);
                ReportPropertyChanging("country_code");
                _country_code = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("country_code");
                Oncountry_codeChanged();
            }
        }
        private global::System.Int32 _country_code;
        partial void Oncountry_codeChanging(global::System.Int32 value);
        partial void Oncountry_codeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();

        #endregion
    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("WinesModel", "WineRegion", "Wine")]
        public EntityCollection<Wine> Wine
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Wine>("WinesModel.WineRegion", "Wine");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Wine>("WinesModel.WineRegion", "Wine", value);
                }
            }
        }
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("WinesModel", "CountryRegion", "Country")]
        public Country Country
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Country>("WinesModel.CountryRegion", "Country").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Country>("WinesModel.CountryRegion", "Country").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Country> CountryReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Country>("WinesModel.CountryRegion", "Country");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Country>("WinesModel.CountryRegion", "Country", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="WinesModel", Name="Taste")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Taste : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 Taste 对象。
        /// </summary>
        /// <param name="taste_id">taste_id 属性的初始值。</param>
        /// <param name="color_code">color_code 属性的初始值。</param>
        /// <param name="taste_description">taste_description 属性的初始值。</param>
        public static Taste CreateTaste(global::System.Int32 taste_id, global::System.Int32 color_code, global::System.String taste_description)
        {
            Taste taste = new Taste();
            taste.taste_id = taste_id;
            taste.color_code = color_code;
            taste.taste_description = taste_description;
            return taste;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 taste_id
        {
            get
            {
                return _taste_id;
            }
            set
            {
                if (_taste_id != value)
                {
                    Ontaste_idChanging(value);
                    ReportPropertyChanging("taste_id");
                    _taste_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("taste_id");
                    Ontaste_idChanged();
                }
            }
        }
        private global::System.Int32 _taste_id;
        partial void Ontaste_idChanging(global::System.Int32 value);
        partial void Ontaste_idChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 color_code
        {
            get
            {
                return _color_code;
            }
            set
            {
                Oncolor_codeChanging(value);
                ReportPropertyChanging("color_code");
                _color_code = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("color_code");
                Oncolor_codeChanged();
            }
        }
        private global::System.Int32 _color_code;
        partial void Oncolor_codeChanging(global::System.Int32 value);
        partial void Oncolor_codeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String taste_description
        {
            get
            {
                return _taste_description;
            }
            set
            {
                Ontaste_descriptionChanging(value);
                ReportPropertyChanging("taste_description");
                _taste_description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("taste_description");
                Ontaste_descriptionChanged();
            }
        }
        private global::System.String _taste_description;
        partial void Ontaste_descriptionChanging(global::System.String value);
        partial void Ontaste_descriptionChanged();

        #endregion
    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("WinesModel", "WineTaste", "Wine")]
        public EntityCollection<Wine> Wine
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Wine>("WinesModel.WineTaste", "Wine");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Wine>("WinesModel.WineTaste", "Wine", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="WinesModel", Name="Wine")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Wine : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 Wine 对象。
        /// </summary>
        /// <param name="wine_id">wine_id 属性的初始值。</param>
        /// <param name="mood_code">mood_code 属性的初始值。</param>
        /// <param name="taste_code">taste_code 属性的初始值。</param>
        /// <param name="color_code">color_code 属性的初始值。</param>
        /// <param name="years_code">years_code 属性的初始值。</param>
        /// <param name="country_code">country_code 属性的初始值。</param>
        /// <param name="region_code">region_code 属性的初始值。</param>
        /// <param name="name">name 属性的初始值。</param>
        /// <param name="description">description 属性的初始值。</param>
        /// <param name="pic_url">pic_url 属性的初始值。</param>
        /// <param name="price">price 属性的初始值。</param>
        public static Wine CreateWine(global::System.Int32 wine_id, global::System.Int32 mood_code, global::System.Int32 taste_code, global::System.Int32 color_code, global::System.Int32 years_code, global::System.Int32 country_code, global::System.Int32 region_code, global::System.String name, global::System.String description, global::System.String pic_url, global::System.String price)
        {
            Wine wine = new Wine();
            wine.wine_id = wine_id;
            wine.mood_code = mood_code;
            wine.taste_code = taste_code;
            wine.color_code = color_code;
            wine.years_code = years_code;
            wine.country_code = country_code;
            wine.region_code = region_code;
            wine.name = name;
            wine.description = description;
            wine.pic_url = pic_url;
            wine.price = price;
            return wine;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 wine_id
        {
            get
            {
                return _wine_id;
            }
            set
            {
                if (_wine_id != value)
                {
                    Onwine_idChanging(value);
                    ReportPropertyChanging("wine_id");
                    _wine_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("wine_id");
                    Onwine_idChanged();
                }
            }
        }
        private global::System.Int32 _wine_id;
        partial void Onwine_idChanging(global::System.Int32 value);
        partial void Onwine_idChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 mood_code
        {
            get
            {
                return _mood_code;
            }
            set
            {
                Onmood_codeChanging(value);
                ReportPropertyChanging("mood_code");
                _mood_code = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("mood_code");
                Onmood_codeChanged();
            }
        }
        private global::System.Int32 _mood_code;
        partial void Onmood_codeChanging(global::System.Int32 value);
        partial void Onmood_codeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 taste_code
        {
            get
            {
                return _taste_code;
            }
            set
            {
                Ontaste_codeChanging(value);
                ReportPropertyChanging("taste_code");
                _taste_code = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("taste_code");
                Ontaste_codeChanged();
            }
        }
        private global::System.Int32 _taste_code;
        partial void Ontaste_codeChanging(global::System.Int32 value);
        partial void Ontaste_codeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 color_code
        {
            get
            {
                return _color_code;
            }
            set
            {
                Oncolor_codeChanging(value);
                ReportPropertyChanging("color_code");
                _color_code = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("color_code");
                Oncolor_codeChanged();
            }
        }
        private global::System.Int32 _color_code;
        partial void Oncolor_codeChanging(global::System.Int32 value);
        partial void Oncolor_codeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 years_code
        {
            get
            {
                return _years_code;
            }
            set
            {
                Onyears_codeChanging(value);
                ReportPropertyChanging("years_code");
                _years_code = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("years_code");
                Onyears_codeChanged();
            }
        }
        private global::System.Int32 _years_code;
        partial void Onyears_codeChanging(global::System.Int32 value);
        partial void Onyears_codeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 country_code
        {
            get
            {
                return _country_code;
            }
            set
            {
                Oncountry_codeChanging(value);
                ReportPropertyChanging("country_code");
                _country_code = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("country_code");
                Oncountry_codeChanged();
            }
        }
        private global::System.Int32 _country_code;
        partial void Oncountry_codeChanging(global::System.Int32 value);
        partial void Oncountry_codeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 region_code
        {
            get
            {
                return _region_code;
            }
            set
            {
                Onregion_codeChanging(value);
                ReportPropertyChanging("region_code");
                _region_code = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("region_code");
                Onregion_codeChanged();
            }
        }
        private global::System.Int32 _region_code;
        partial void Onregion_codeChanging(global::System.Int32 value);
        partial void Onregion_codeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String description
        {
            get
            {
                return _description;
            }
            set
            {
                OndescriptionChanging(value);
                ReportPropertyChanging("description");
                _description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("description");
                OndescriptionChanged();
            }
        }
        private global::System.String _description;
        partial void OndescriptionChanging(global::System.String value);
        partial void OndescriptionChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String pic_url
        {
            get
            {
                return _pic_url;
            }
            set
            {
                Onpic_urlChanging(value);
                ReportPropertyChanging("pic_url");
                _pic_url = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("pic_url");
                Onpic_urlChanged();
            }
        }
        private global::System.String _pic_url;
        partial void Onpic_urlChanging(global::System.String value);
        partial void Onpic_urlChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String price
        {
            get
            {
                return _price;
            }
            set
            {
                OnpriceChanging(value);
                ReportPropertyChanging("price");
                _price = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("price");
                OnpriceChanged();
            }
        }
        private global::System.String _price;
        partial void OnpriceChanging(global::System.String value);
        partial void OnpriceChanged();

        #endregion
    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("WinesModel", "WineYear", "Year")]
        public Year Year
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Year>("WinesModel.WineYear", "Year").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Year>("WinesModel.WineYear", "Year").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Year> YearReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Year>("WinesModel.WineYear", "Year");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Year>("WinesModel.WineYear", "Year", value);
                }
            }
        }
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("WinesModel", "WineTaste", "Taste")]
        public Taste Taste
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Taste>("WinesModel.WineTaste", "Taste").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Taste>("WinesModel.WineTaste", "Taste").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Taste> TasteReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Taste>("WinesModel.WineTaste", "Taste");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Taste>("WinesModel.WineTaste", "Taste", value);
                }
            }
        }
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("WinesModel", "WineColor", "Color")]
        public Color Color
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Color>("WinesModel.WineColor", "Color").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Color>("WinesModel.WineColor", "Color").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Color> ColorReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Color>("WinesModel.WineColor", "Color");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Color>("WinesModel.WineColor", "Color", value);
                }
            }
        }
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("WinesModel", "WineCountry", "Country")]
        public Country Country
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Country>("WinesModel.WineCountry", "Country").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Country>("WinesModel.WineCountry", "Country").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Country> CountryReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Country>("WinesModel.WineCountry", "Country");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Country>("WinesModel.WineCountry", "Country", value);
                }
            }
        }
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("WinesModel", "WineRegion", "Region")]
        public Region Region
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Region>("WinesModel.WineRegion", "Region").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Region>("WinesModel.WineRegion", "Region").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Region> RegionReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Region>("WinesModel.WineRegion", "Region");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Region>("WinesModel.WineRegion", "Region", value);
                }
            }
        }
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("WinesModel", "WineWMMW", "WMMW")]
        public EntityCollection<WMMW> WMMWs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<WMMW>("WinesModel.WineWMMW", "WMMW");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<WMMW>("WinesModel.WineWMMW", "WMMW", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="WinesModel", Name="WMMW")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class WMMW : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 WMMW 对象。
        /// </summary>
        /// <param name="wineId">WineId 属性的初始值。</param>
        /// <param name="moodId">MoodId 属性的初始值。</param>
        /// <param name="id">ID 属性的初始值。</param>
        public static WMMW CreateWMMW(global::System.Int32 wineId, global::System.Int32 moodId, global::System.Int32 id)
        {
            WMMW wMMW = new WMMW();
            wMMW.WineId = wineId;
            wMMW.MoodId = moodId;
            wMMW.ID = id;
            return wMMW;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 WineId
        {
            get
            {
                return _WineId;
            }
            set
            {
                OnWineIdChanging(value);
                ReportPropertyChanging("WineId");
                _WineId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("WineId");
                OnWineIdChanged();
            }
        }
        private global::System.Int32 _WineId;
        partial void OnWineIdChanging(global::System.Int32 value);
        partial void OnWineIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MoodId
        {
            get
            {
                return _MoodId;
            }
            set
            {
                OnMoodIdChanging(value);
                ReportPropertyChanging("MoodId");
                _MoodId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MoodId");
                OnMoodIdChanged();
            }
        }
        private global::System.Int32 _MoodId;
        partial void OnMoodIdChanging(global::System.Int32 value);
        partial void OnMoodIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();

        #endregion
    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("WinesModel", "MoodWMMW", "Mood")]
        public Mood Mood
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Mood>("WinesModel.MoodWMMW", "Mood").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Mood>("WinesModel.MoodWMMW", "Mood").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Mood> MoodReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Mood>("WinesModel.MoodWMMW", "Mood");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Mood>("WinesModel.MoodWMMW", "Mood", value);
                }
            }
        }
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("WinesModel", "WineWMMW", "Wine")]
        public Wine Wine
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Wine>("WinesModel.WineWMMW", "Wine").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Wine>("WinesModel.WineWMMW", "Wine").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Wine> WineReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Wine>("WinesModel.WineWMMW", "Wine");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Wine>("WinesModel.WineWMMW", "Wine", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="WinesModel", Name="Year")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Year : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 Year 对象。
        /// </summary>
        /// <param name="year_id">year_id 属性的初始值。</param>
        public static Year CreateYear(global::System.Int32 year_id)
        {
            Year year = new Year();
            year.year_id = year_id;
            return year;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 year_id
        {
            get
            {
                return _year_id;
            }
            set
            {
                if (_year_id != value)
                {
                    Onyear_idChanging(value);
                    ReportPropertyChanging("year_id");
                    _year_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("year_id");
                    Onyear_idChanged();
                }
            }
        }
        private global::System.Int32 _year_id;
        partial void Onyear_idChanging(global::System.Int32 value);
        partial void Onyear_idChanged();

        #endregion
    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("WinesModel", "WineYear", "Wine")]
        public EntityCollection<Wine> Wine
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Wine>("WinesModel.WineYear", "Wine");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Wine>("WinesModel.WineYear", "Wine", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
