//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Runtime.Serialization;

namespace ServiceDataLib
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(Wine))]
    public partial class Color
    {
        #region Primitive Properties
        [DataMember]
        public virtual int color_id
        {
            get;
            set;
        }
        [DataMember]
        public virtual string color_description
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
        
    
        [DataMember]
        public virtual ICollection<Wine> Wine
        {
            get
            {
                if (_wine == null)
                {
                    var newCollection = new FixupCollection<Wine>();
                    newCollection.CollectionChanged += FixupWine;
                    _wine = newCollection;
                }
                return _wine;
            }
            set
            {
                if (!ReferenceEquals(_wine, value))
                {
                    var previousValue = _wine as FixupCollection<Wine>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupWine;
                    }
                    _wine = value;
                    var newValue = value as FixupCollection<Wine>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupWine;
                    }
                }
            }
        }
        private ICollection<Wine> _wine;

        #endregion
        #region Association Fixup
    
        private void FixupWine(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Wine item in e.NewItems)
                {
                    item.Color = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Wine item in e.OldItems)
                {
                    if (ReferenceEquals(item.Color, this))
                    {
                        item.Color = null;
                    }
                }
            }
        }

        #endregion
    }
}
