//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Runtime.Serialization;

namespace ServiceDataLib
{
    [DataContract(IsReference = true)]
    public partial class FriendStatus
    {
        #region Primitive Properties
        [DataMember]
        public virtual int FriendStatusId
        {
            get;
            set;
        }
        [DataMember]
        public virtual int FromUserId
        {
            get;
            set;
        }
        [DataMember]
        public virtual int ToUserId
        {
            get;
            set;
        }
        [DataMember]
        public virtual byte StatusId
        {
            get;
            set;
        }
        [DataMember]
        public virtual System.DateTime SentTime
        {
            get;
            set;
        }
        [DataMember]
        public virtual System.DateTime ResponseTime
        {
            get;
            set;
        }

        #endregion
    }
}
