//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Runtime.Serialization;

namespace ServiceDataLib
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(WMMW))]
    public partial class Mood
    {
        #region Primitive Properties
        [DataMember]
        public virtual int mood_id
        {
            get;
            set;
        }
        [DataMember]
        public virtual string mood_description
        {
            get;
            set;
        }
        [DataMember]
        public virtual string wine_code
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
        
    
        [DataMember]
        public virtual ICollection<WMMW> WMMWs
        {
            get
            {
                if (_wMMWs == null)
                {
                    var newCollection = new FixupCollection<WMMW>();
                    newCollection.CollectionChanged += FixupWMMWs;
                    _wMMWs = newCollection;
                }
                return _wMMWs;
            }
            set
            {
                if (!ReferenceEquals(_wMMWs, value))
                {
                    var previousValue = _wMMWs as FixupCollection<WMMW>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupWMMWs;
                    }
                    _wMMWs = value;
                    var newValue = value as FixupCollection<WMMW>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupWMMWs;
                    }
                }
            }
        }
        private ICollection<WMMW> _wMMWs;

        #endregion
        #region Association Fixup
    
        private void FixupWMMWs(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (WMMW item in e.NewItems)
                {
                    item.Mood = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (WMMW item in e.OldItems)
                {
                    if (ReferenceEquals(item.Mood, this))
                    {
                        item.Mood = null;
                    }
                }
            }
        }

        #endregion
    }
}
