//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Runtime.Serialization;

namespace ServiceDataLib
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(Post))]
    [KnownType(typeof(User))]
    public partial class Reply
    {
        #region Primitive Properties
        [DataMember]
        public virtual int reply_id
        {
            get;
            set;
        }
        [DataMember]
        public virtual int post_code
        {
            get { return _post_code; }
            set
            {
                if (_post_code != value)
                {
                    if (Post != null && Post.post_id != value)
                    {
                        Post = null;
                    }
                    _post_code = value;
                }
            }
        }
        private int _post_code;
        [DataMember]
        public virtual string texts
        {
            get;
            set;
        }
        [DataMember]
        public virtual int user_code
        {
            get { return _user_code; }
            set
            {
                if (_user_code != value)
                {
                    if (User != null && User.user_id != value)
                    {
                        User = null;
                    }
                    _user_code = value;
                }
            }
        }
        private int _user_code;
        [DataMember]
        public virtual System.DateTime post_date
        {
            get;
            set;
        }
        [DataMember]
        public virtual string post_ip
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
        
    
        [DataMember]
        public virtual Post Post
        {
            get { return _post; }
            set
            {
                if (!ReferenceEquals(_post, value))
                {
                    var previousValue = _post;
                    _post = value;
                    FixupPost(previousValue);
                }
            }
        }
        private Post _post;
        
    
        [DataMember]
        public virtual User User
        {
            get { return _user; }
            set
            {
                if (!ReferenceEquals(_user, value))
                {
                    var previousValue = _user;
                    _user = value;
                    FixupUser(previousValue);
                }
            }
        }
        private User _user;

        #endregion
        #region Association Fixup
    
        private void FixupPost(Post previousValue)
        {
            if (previousValue != null && previousValue.Replies.Contains(this))
            {
                previousValue.Replies.Remove(this);
            }
    
            if (Post != null)
            {
                if (!Post.Replies.Contains(this))
                {
                    Post.Replies.Add(this);
                }
                if (post_code != Post.post_id)
                {
                    post_code = Post.post_id;
                }
            }
        }
    
        private void FixupUser(User previousValue)
        {
            if (previousValue != null && previousValue.Replies.Contains(this))
            {
                previousValue.Replies.Remove(this);
            }
    
            if (User != null)
            {
                if (!User.Replies.Contains(this))
                {
                    User.Replies.Add(this);
                }
                if (user_code != User.user_id)
                {
                    user_code = User.user_id;
                }
            }
        }

        #endregion
    }
}
