//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Runtime.Serialization;

namespace ServiceDataLib
{
    [DataContract(IsReference = true)]
    public partial class sim_mat
    {
        #region Primitive Properties
        [DataMember]
        public virtual int ID
        {
            get;
            set;
        }
        [DataMember]
        public virtual decimal agePercent
        {
            get;
            set;
        }
        [DataMember]
        public virtual string wine_sim
        {
            get;
            set;
        }
        [DataMember]
        public virtual decimal simPercent
        {
            get;
            set;
        }

        #endregion
    }
}
